version: '2'
services:
  redis-data:
    image: clescot/rancher-redis:28
    stdin_open: true
    volumes:
    - /data
    tty: true
    command:
    - cat
  redis-sentinel:
    image: clescot/rancher-redis-sentinel:3
    ports:
    - 51010:26379/tcp
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    depends_on:
    - redis
  redis:
    image: clescot/rancher-redis:28
    volumes_from:
    - redis-data
    ports:
    - 50907:6379/tcp
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: redis-data
