version: '2'
services:
  redis-data:
    image: registry.cn-beijing.aliyuncs.com/andyyoung01/rancher-redis:3.2.0
    stdin_open: true
    volumes:
    - /data
    tty: true
    command:
    - cat
  redis-sentinel:
    image: registry.cn-beijing.aliyuncs.com/andyyoung01/rancher-redis-sentinel:4.0.1
    ports:
    - 51010:26379/tcp
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
    depends_on:
    - redis
  redis:
    image: registry.cn-beijing.aliyuncs.com/andyyoung01/rancher-redis:3.2.0
    volumes_from:
    - redis-data
    ports:
    - 50907:6379/tcp
    labels:
      io.rancher.scheduler.affinity:container_label_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.sidekicks: redis-data
